version: "3.9"

services:
  backend:
    image: backend:1.0.0
    container_name: backdeclitech
    ports:
      - "8089:8089"
    pull_policy: "never"   # Utilise l'image locale
    environment:
      SPRING_PROFILES_ACTIVE: build
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/declitech_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""        # mot de passe vide
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql-declitech
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"   # autorise le mot de passe vide (ONLY dev)
      MYSQL_DATABASE: declitech_db
      MYSQL_ROOT_HOST: '%'                 # permet connexions externes
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  mysql-data:
