spring.application.name=BackDeclitech

# Server configuration
server.servlet.context-path=/declitech
server.port=8089

### LOCAL DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/declitech_db2?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


### DATABASE ###
# spring.datasource.url=jdbc:postgresql://hopper.proxy.rlwy.net:18500/railway
# spring.datasource.username=postgres
# spring.datasource.password=biCTyIEjfkJtAoBxJIFovaldGlHnCHMZ

### JPA / HIBERNATE ###
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# JWT Configuration (MOVE SECRET OUT OF CODE!)
jwt.secret=${JWT_SECRET:ma-cle-tres-secrete-pour-jwt-qui-doit-etre-longue-1234}
jwt.expiration=3600000
jwt.refresh-expiration=604800000


# Configuration Email - Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=farah.telli@esprit.tn
spring.mail.password=jjgk qvft lcns vbjh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Configuration Async pour les emails
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=5
spring.task.execution.pool.queue-capacity=100


spring.jpa.properties.hibernate.format_sql=true
