spring.application.name=BackDeclitech

# Server configuration
server.servlet.context-path=/declitech
server.port=8089

### LOCAL DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/declitech_db2?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


### DATABASE ###
# spring.datasource.url=jdbc:postgresql://hopper.proxy.rlwy.net:18500/railway
# spring.datasource.username=postgres
# spring.datasource.password=biCTyIEjfkJtAoBxJIFovaldGlHnCHMZ

### JPA / HIBERNATE ###
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



spring.jpa.properties.hibernate.format_sql=true